QN.1

In [11]:
import pandas as pd
import numpy as np

# Create 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)


[1 2 3 4 5]


QN.2

In [4]:
# Create 2D array (3x3) of consecutive integers
arr_2d = np.arange(1, 10).reshape(3, 3)
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


QN.3

In [5]:
# Array operations
mean_value = np.mean(arr_1d)
std_dev = np.std(arr_1d)
max_value = np.max(arr_1d)

print("Mean:", mean_value)
print("Standard Deviation:", std_dev)
print("Max Value:", max_value)

Mean: 3.0
Standard Deviation: 1.4142135623730951
Max Value: 5


QN.4

In [6]:
# Load CSV file
df = pd.read_csv('/content/sample-data.csv')
print(df)


                  Name  Age  Salary          Department  Experience  \
0        Emily Johnson   28   55000           Marketing           4   
1         Michael Chen   35   72000         Engineering           8   
2      Sarah Rodriguez   42   88000               Sales          15   
3            David Kim   31   62000                  IT           6   
4      Rachel Thompson   26   48000    Customer Support           3   
5           Alex Patel   39   95000             Finance          12   
6         Jessica Wong   33   67000                  HR           7   
7         Kevin Nguyen   45  105000  Product Management          18   
8           Lisa Brown   29   58000              Design           5   
9        Robert Garcia   37   81000          Operations          11   
10          Amanda Lee   24   42000           Marketing           2   
11  Christopher Taylor   40   92000               Sales          14   
12     Olivia Martinez   27   52000    Customer Support           4   
13    

QN.5

In [7]:
# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())

# Fill missing values with 0
df.fillna(0, inplace=True)
print(df)


Missing values per column:
Name          0
Age           0
Salary        0
Department    0
Experience    0
Education     0
dtype: int64
                  Name  Age  Salary          Department  Experience  \
0        Emily Johnson   28   55000           Marketing           4   
1         Michael Chen   35   72000         Engineering           8   
2      Sarah Rodriguez   42   88000               Sales          15   
3            David Kim   31   62000                  IT           6   
4      Rachel Thompson   26   48000    Customer Support           3   
5           Alex Patel   39   95000             Finance          12   
6         Jessica Wong   33   67000                  HR           7   
7         Kevin Nguyen   45  105000  Product Management          18   
8           Lisa Brown   29   58000              Design           5   
9        Robert Garcia   37   81000          Operations          11   
10          Amanda Lee   24   42000           Marketing           2   
11  Christop

QN.6

In [9]:
# Select columns 'Age' and 'Name' and the first 5 rows
selected_data = df[['Name', 'Age']].iloc[:5]
print(selected_data)


              Name  Age
0    Emily Johnson   28
1     Michael Chen   35
2  Sarah Rodriguez   42
3        David Kim   31
4  Rachel Thompson   26


QN.7

In [10]:
# Rename columns
df.rename(columns={'Name': 'Names'}, inplace=True)
print(df)


                 Names  Age  Salary          Department  Experience  \
0        Emily Johnson   28   55000           Marketing           4   
1         Michael Chen   35   72000         Engineering           8   
2      Sarah Rodriguez   42   88000               Sales          15   
3            David Kim   31   62000                  IT           6   
4      Rachel Thompson   26   48000    Customer Support           3   
5           Alex Patel   39   95000             Finance          12   
6         Jessica Wong   33   67000                  HR           7   
7         Kevin Nguyen   45  105000  Product Management          18   
8           Lisa Brown   29   58000              Design           5   
9        Robert Garcia   37   81000          Operations          11   
10          Amanda Lee   24   42000           Marketing           2   
11  Christopher Taylor   40   92000               Sales          14   
12     Olivia Martinez   27   52000    Customer Support           4   
13    